#*****************************************************************************************
# Vivado (TM) v2019.1 (64-bit)
#
# xuantie.tcl: Tcl script for re-creating project 'xuantie'
#
# Generated by Vivado on Mon May 16 00:02:48 CDT 2022
# IP Build 2548770 on Fri May 24 18:01:18 MDT 2019
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (xuantie.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************
### Modify origin_dir before source the script
# Set the reference directory for source file relative paths (by default the value is script directory path)
##set origin_dir "."
###

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "xuantie"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "xuantie.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/A00XuanTie-C910-FPGA/xuantie"]"

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xc7vx485tffg1761-2

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Set project properties
set obj [current_project]
set_property -name "board_part" -value "xilinx.com:vc707:part0:1.4" -objects $obj
set_property -name "default_lib" -value "xil_defaultlib" -objects $obj
set_property -name "dsa.accelerator_binary_content" -value "bitstream" -objects $obj
set_property -name "dsa.accelerator_binary_format" -value "xclbin2" -objects $obj
set_property -name "dsa.board_id" -value "vc707" -objects $obj
set_property -name "dsa.description" -value "Vivado generated DSA" -objects $obj
set_property -name "dsa.dr_bd_base_address" -value "0" -objects $obj
set_property -name "dsa.emu_dir" -value "emu" -objects $obj
set_property -name "dsa.flash_interface_type" -value "bpix16" -objects $obj
set_property -name "dsa.flash_offset_address" -value "0" -objects $obj
set_property -name "dsa.flash_size" -value "1024" -objects $obj
set_property -name "dsa.host_architecture" -value "x86_64" -objects $obj
set_property -name "dsa.host_interface" -value "pcie" -objects $obj
set_property -name "dsa.num_compute_units" -value "60" -objects $obj
set_property -name "dsa.platform_state" -value "pre_synth" -objects $obj
set_property -name "dsa.vendor" -value "xilinx" -objects $obj
set_property -name "dsa.version" -value "0.0" -objects $obj
set_property -name "enable_vhdl_2008" -value "1" -objects $obj
set_property -name "ip_cache_permissions" -value "read write" -objects $obj
set_property -name "ip_output_repo" -value "$proj_dir/${_xil_proj_name_}.cache/ip" -objects $obj
set_property -name "mem.enable_memory_map_generation" -value "1" -objects $obj
set_property -name "sim.central_dir" -value "$proj_dir/${_xil_proj_name_}.ip_user_files" -objects $obj
set_property -name "sim.ip.auto_export_scripts" -value "1" -objects $obj
set_property -name "simulator_language" -value "Mixed" -objects $obj

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/common/rtl/BUFGCE.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/common/rtl/booth_code.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/common/rtl/booth_code_v1.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/common/rtl/compressor_32.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/common/rtl/compressor_42.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/plic/rtl/csky_apb_1tox_matrix.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/biu/rtl/ct_biu_csr_req_arbiter.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/biu/rtl/ct_biu_lowpower.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/biu/rtl/ct_biu_other_io_sync.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cpu/rtl/cpu_cfig.h"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/biu/rtl/ct_biu_read_channel.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/biu/rtl/ct_biu_req_arbiter.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/biu/rtl/ct_biu_snoop_channel.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/biu/rtl/ct_biu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/biu/rtl/ct_biu_write_channel.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_apbif.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_bmbif.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_bmbif_kid.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_ctcq.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_ctcq_reqq_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_ctcq_respq_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_ebiuif.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_l2cif.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_ncq.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_ncq_gm.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_regs.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_regs_kid.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_snb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_snb_arb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_snb_dp_sel.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_snb_dp_sel_16.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_snb_dp_sel_8.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_snb_sab.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_snb_sab_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_vb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ciu_vb_aw_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/clint/rtl/ct_clint_func.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/clint/rtl/ct_clint_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/clk/rtl/ct_clk_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cpu/rtl/ct_core.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cp0/rtl/ct_cp0_iui.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cp0/rtl/ct_cp0_lpmd.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cp0/rtl/ct_cp0_regs.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cp0/rtl/ct_cp0_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ebiu_cawt_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ebiu_lowpower.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ebiu_ncwt_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ebiu_read_channel.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ebiu_snoop_channel_dummy.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ebiu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_ebiu_write_channel.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_1024x64.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_128x16.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_2048x32.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_256x196.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_256x23.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_256x84.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_512x144.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_512x22.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_512x44.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_512x52.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_512x54.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_512x59.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_512x7.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_512x96.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_8192x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fadd_close_s0_d.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fadd_close_s0_h.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fadd_close_s1_d.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fadd_close_s1_h.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fadd_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fadd_double_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fadd_half_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fadd_onehot_sel_d.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fadd_onehot_sel_h.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fadd_scalar_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fadd_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fcnvt_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fcnvt_double_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fcnvt_dtoh_sh.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fcnvt_dtos_sh.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fcnvt_ftoi_sh.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fcnvt_htos_sh.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fcnvt_itof_sh.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fcnvt_scalar_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fcnvt_stod_sh.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fcnvt_stoh_sh.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fcnvt_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_fifo.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fspu_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fspu_double.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fspu_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fspu_half.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fspu_single.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_fspu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_bkpt.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_common_dbg_info.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_common_regs.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_common_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_dbg_info.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_ddc_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_ddc_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_etm.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_etm_if.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_event.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_io.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_ir.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_nirv_bkpt.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_pcfifo.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_private_ir.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_private_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_regs.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_serial.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_sm.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_sync_3flop.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/had/rtl/ct_had_trace.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/pmu/rtl/ct_hpcp_adder_sel.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/pmu/rtl/ct_hpcp_cnt.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/pmu/rtl/ct_hpcp_cntinten_reg.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/pmu/rtl/ct_hpcp_cntof_reg.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/pmu/rtl/ct_hpcp_event.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/pmu/rtl/ct_hpcp_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_dep_reg_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_dep_reg_src2_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_dep_vreg_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_dep_vreg_srcv2_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_id_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_id_decd.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_id_decd_special.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_id_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_id_fence.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_id_split_long.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_id_split_short.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_ir_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_ir_decd.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_ir_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_ir_frt.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_ir_rt.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_ir_vrt.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_aiq0.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_aiq0_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_aiq1.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_aiq1_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_aiq_lch_rdy_1.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_aiq_lch_rdy_2.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_aiq_lch_rdy_3.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_biq.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_biq_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_lsiq.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_lsiq_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_pipe_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_sdiq.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_sdiq_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_viq0.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_viq0_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_viq1.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_is_viq1_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_fwd.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_fwd_preg.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_fwd_vreg.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_pipe0_decd.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_pipe1_decd.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_pipe2_decd.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_pipe3_decd.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_pipe4_decd.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_pipe6_decd.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_pipe7_decd.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_prf_eregfile.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_prf_fregfile.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_prf_gated_ereg.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_prf_gated_preg.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_prf_gated_vreg.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_prf_pregfile.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_rf_prf_vregfile.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/idu/rtl/ct_idu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_addrgen.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_bht.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_bht_pre_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_bht_sel_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_btb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_btb_data_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_btb_tag_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_debug.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_decd_normal.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ibctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ibdp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ibuf.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ibuf_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_icache_data_array0.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_icache_data_array1.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_icache_if.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_icache_predecd_array0.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_icache_predecd_array1.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_icache_tag_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ifctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ifdp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ind_btb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ind_btb_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ipb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ipctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ipdecode.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ipdp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_l0_btb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_l0_btb_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_l1_refill.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_lbuf.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_lbuf_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_pcfifo_if.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_pcgen.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_precode.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_ras.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_sfp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_sfp_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_ifu_vector.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_alu.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_bju.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_bju_pcfifo.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_bju_pcfifo_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_bju_pcfifo_read_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_cbus.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_div.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_div_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_div_srt_radix16.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_mult.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_rbus.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_special.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/ct_iu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2c_cmp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2c_data.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2c_icc.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2c_prefetch.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2c_sub_bank.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2c_tag.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2c_tag_ecc.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2c_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2c_wb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2cache_data_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2cache_dirty_array_16way.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2cache_tag_array_16way.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_l2cache_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_amr.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_bus_arb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_cache_buffer.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_dcache_arb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_dcache_data_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_dcache_dirty_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_dcache_info_update.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_dcache_ld_tag_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_dcache_tag_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_dcache_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_icc.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_idfifo_8.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_idfifo_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_ld_ag.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_ld_da.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_ld_dc.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_ld_wb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_lfb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_lfb_addr_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_lfb_data_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_lm.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_lq.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_lq_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_mcic.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_pfu.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_pfu_gpfb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_pfu_gsdb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_pfu_pfb_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_pfu_pfb_l1sm.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_pfu_pfb_l2sm.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_pfu_pfb_tsm.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_pfu_pmb_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_pfu_sdb_cmp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_pfu_sdb_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_rb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_rb_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_rot_data.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_sd_ex1.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_snoop_ctcq.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_snoop_ctcq_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_snoop_req_arbiter.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_snoop_resp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_snoop_snq.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_snoop_snq_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_spec_fail_predict.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_sq.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_sq_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_st_ag.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_st_da.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_st_dc.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_st_wb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_vb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_vb_addr_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_vb_sdb_data.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_vb_sdb_data_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_wmb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_wmb_ce.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_lsu_wmb_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_arb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_dplru.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_dutlb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_dutlb_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_dutlb_huge_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_dutlb_read.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_iplru.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_iutlb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_iutlb_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_iutlb_fst_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_jtlb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_jtlb_data_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_jtlb_tag_array.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_ptw.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_regs.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/sysmap.h"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_sysmap.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_sysmap_hit.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_tlboper.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_mmu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/clk/rtl/ct_mp_clk_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rst/rtl/ct_mp_rst_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_piu_other_io.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_piu_other_io_dummy.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_piu_other_io_sync.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_piu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_piu_top_dummy.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_piu_top_dummy_device.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/pmp/rtl/ct_pmp_acc.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/pmp/rtl/ct_pmp_comp_hit.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/pmp/rtl/ct_pmp_regs.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/pmp/rtl/ct_pmp_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ciu/rtl/ct_prio.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cpu/rtl/ct_rmu_top_dummy.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rst/rtl/ct_rst_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_compare_iid.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_encode_32.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_encode_64.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_encode_8.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_encode_96.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_expand_32.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_expand_64.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_expand_8.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_expand_96.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_pst_ereg.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_pst_ereg_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_pst_preg.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_pst_preg_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_pst_vreg.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_pst_vreg_dummy.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_pst_vreg_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_retire.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_rob.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_rob_entry.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_rob_expt.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_rob_rt.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/rtu/rtl/ct_rtu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_spsram_1024x64.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_spsram_128x16.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_spsram_2048x32.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_spsram_2048x32_split.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_spsram_256x196.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_spsram_256x23.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/ct_spsram_256x84.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_512x144.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_spsram_512x22.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_spsram_512x44.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_spsram_512x52.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_spsram_512x54.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_spsram_512x59.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_spsram_512x7.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_512x96.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_8192x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cpu/rtl/ct_sysio_kid.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cpu/rtl/ct_sysio_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cpu/rtl/ct_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_vfalu_dp_pipe6.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_vfalu_dp_pipe7.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_vfalu_top_pipe6.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfalu/rtl/ct_vfalu_top_pipe7.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfdsu/rtl/ct_vfdsu_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfdsu/rtl/ct_vfdsu_double.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfdsu/rtl/ct_vfdsu_ff1.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfdsu/rtl/ct_vfdsu_pack.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfdsu/rtl/ct_vfdsu_prepare.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfdsu/rtl/ct_vfdsu_round.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfdsu/rtl/ct_vfdsu_scalar_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfdsu/rtl/ct_vfdsu_srt.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_bound_table.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_only_div.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfdsu/rtl/ct_vfdsu_srt_radix16_with_sqrt.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfdsu/rtl/ct_vfdsu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfmau/rtl/ct_vfmau_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfmau/rtl/ct_vfmau_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfmau/rtl/ct_vfmau_ff1_10bit.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfmau/rtl/ct_vfmau_lza.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfmau/rtl/ct_vfmau_lza_32.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfmau/rtl/ct_vfmau_lza_42.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfmau/rtl/ct_vfmau_lza_simd_half.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfmau/rtl/ct_vfmau_mult1.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfmau/rtl/ct_vfmau_mult_compressor.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfmau/rtl/ct_vfmau_mult_simd_half.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfmau/rtl/ct_vfmau_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfpu/rtl/ct_vfpu_cbus.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfpu/rtl/ct_vfpu_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfpu/rtl/ct_vfpu_dp.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfpu/rtl/ct_vfpu_rbus.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/vfpu/rtl/ct_vfpu_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/fpga_ram.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/clk/rtl/gated_clk_cell.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/iu/rtl/multiplier_65x65_3_stage.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/plic/rtl/plic_32to1_arb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/plic/rtl/plic_arb_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/plic/rtl/plic_ctrl.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/plic/rtl/plic_granu2_arb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/plic/rtl/plic_granu_arb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/plic/rtl/plic_hart_arb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/plic/rtl/plic_hreg_busif.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/plic/rtl/plic_int_kid.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/plic/rtl/plic_kid_busif.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/plic/rtl/plic_top.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/common/rtl/sync_level2level.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/common/rtl/sync_level2pulse.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cpu/rtl/openC910.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_1024x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_1024x144.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_1024x32.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_1024x59.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_1024x92.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_128x104.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_128x144.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_16384x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_2048x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_2048x144.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_2048x59.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_2048x88.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_256x100.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_256x144.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_256x52.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_256x54.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_256x59.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_256x7.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_32768x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_4096x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_4096x144.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_4096x32.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_4096x84.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_64x108.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_65536x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/fpga/rtl/ct_f_spsram_8192x32.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_1024x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_1024x144.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_spsram_1024x32.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_spsram_1024x59.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_1024x92.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_128x104.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_128x144.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_16384x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_2048x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_2048x144.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_spsram_2048x59.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_2048x88.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_256x100.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_256x144.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_spsram_256x52.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_spsram_256x54.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/ifu/rtl/ct_spsram_256x59.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_spsram_256x7.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_32768x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_4096x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_4096x144.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_spsram_4096x32.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_4096x84.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_64x108.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/l2c/rtl/ct_spsram_65536x128.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/lsu/rtl/ct_spsram_8192x32.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cpu/rtl/mp_top_golden_port.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cpu/rtl/top_golden_port.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/rtl/cpu_cfig.h"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/rtl/sysmap.h"]\
]
set imported_files [import_files -fileset sources_1 $files]

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
set file "rtl/cpu_cfig.h"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "rtl/sysmap.h"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "rtl/cpu_cfig.h"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "rtl/sysmap.h"
set file_obj [get_files -of_objects [get_filesets sources_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj


# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "top" -value "openC910" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sim_1/imports/tb/tb.v"]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/mmu/rtl/sysmap.h" ]\
 [file normalize "${origin_dir}/A00XuanTie-C910-FPGA/xuantie/xuantie.srcs/sources_1/imports/gen_rtl/cpu/rtl/cpu_cfig.h" ]\
]
set imported_files [import_files -fileset sim_1 $files]

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
set file "rtl/sysmap.h"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj

set file "rtl/cpu_cfig.h"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "file_type" -value "Verilog Header" -objects $file_obj


# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "top" -value "openC910" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xc7vx485tffg1761-2 -flow {Vivado Synthesis 2019} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2019" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xc7vx485tffg1761-2 -flow {Vivado Implementation 2019} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2019" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
